### ISSUE TITLE
schedule pod crush 

### ISSUE THREAD

**Issue by ramazulay** [D10S0VSkY-OSS/Stack-Lifecycle-Deployment#99]
Hi @D10S0VSkY-OSS,
As I see you update the schedule image, please see the error log:
**kubectl logs schedule-77ddb5d66f-58jt9 -n sld**
INFO      Check_Task Add schedule
INFO      Adding job tentatively -- it will be properly scheduled when the scheduler starts
WARNING   Can't validate in the api-backend, Set user and password bot in api-backend try 999 of 1000
INFO      Get deploy by id 2 - 200 - squad1 - eup-dev
Traceback (most recent call last):
  File "/app/./helpers/get_deploy_schedule.py", line 76, in get_deploy_by_id
    "project_path": response["json"]["project_path"],
KeyError: 'project_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 437, in main
    run(app, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/./main.py", line 11, in <module>
    init_check_schedule()
  File "/app/./helpers/get_deploy_schedule.py", line 51, in init_check_schedule
    raise err
  File "/app/./helpers/get_deploy_schedule.py", line 49, in init_check_schedule
    addDeployToSchedule(i)
  File "/app/./helpers/get_deploy_schedule.py", line 232, in addDeployToSchedule
    data = get_deploy_by_id(deploy_id)
  File "/app/./helpers/get_deploy_schedule.py", line 80, in get_deploy_by_id
    raise HTTPException(status_code=404, detail=f"{err}")
fastapi.exceptions.HTTPException

Thanks.

**Comment by D10S0VSkY-OSS** [comment]
Hi @ramazulay ,
please, colud you check if in database table deploy have project_path item?

thanks!

**Comment by D10S0VSkY-OSS** [comment]
Hi @ramazulay 
Have you been able to solve it?
can we close the issue?

Regards

**Comment by ramazulay** [comment]
Hi @D10S0VSkY-OSS,
I went back to the old version(2.2.0) and that fixed it.

Thanks.
